language: java 
sudo: true  
deploy: 
edge: true 
provider: cloudfoundry 
username: bhartikukreja2015@gmail.com 
password: romaguddu123
api: https://api.run.pivotal.io 
organization: Timesheet 
space: development 
